### ISSUE TITLE
Accessing files when complete

### ISSUE THREAD

**Issue by Lewiscowles1986** [php-actions/composer#17]
So I tried pairing this with the github actions for wordpress plugin deployment and it seems that the vendor folder never comes out the other side of this action... It created a commit that deleted the folder stopping the plugin from working

https://github.com/Lewiscowles1986/WordPressSVGPlugin/runs/1294128965?check_suite_focus=true

**Comment by g105b** [comment]
Hi @Lewiscowles1986,

It looks to me like your action is being stopped by the .gitattributes file being missing, see https://github.com/Lewiscowles1986/WordPressSVGPlugin/runs/1294128965?check_suite_focus=true#step:7:82

To help debug this, you can create a step in your action that outputs the contents of a directory by running `ls`. That would let you see exactly what is in the directory. I am 100% confident that your `vendor` directory has been created correctly, because that's the only real job of composer, and a lot of people rely on this action in their projects.

Let me know how you get on debugging and I'll help you wherever possible.

**Comment by Lewiscowles1986** [comment]
I'm so sorry, it's weirder than that...

Basically the vendor folder gets omitted due to not being part of git and in gitignore.

**Comment by Lewiscowles1986** [comment]
If you want to look at more recent runs I've been doing what I think are some interesting things using this action. Thanks for writing it.
