### ISSUE TITLE
Where I can see the list of PHP extension enabled by default?

### ISSUE THREAD

**Issue by ericknyoto** [php-actions/composer#24]
I have a composer.json that required redis extension installed and enabled.
But the composer install was failed because no redis extension installed.
How can I add the extension?
Thanks.

**Comment by g105b** [comment]
Hi @ericknyoto,

We're currently working on improving the PHP installation process, using our own Docker image. Please see here: https://github.com/php-actions/php-build/blob/master/Dockerfile#L12

I'm trying to figure out the best way to manage the extensions, so that people like yourself can configure the action to have the correct extensions present. Maybe for now it would be a sensible idea to install all available common extensions? I can add the redis extension myself now if that helps, and the new docker image will be detected by your build script.

Greg.

**Comment by baschny** [comment]
@ericknyoto You don't need the extensions enable just to "install the packages". We don't need php-actions/composer maintainer to keep installing more and more extensions to the container just for that use case.

You can do two things to solve this kind of issues in CI at `composer install` time:

a) use `--ignore-platform-reqs` to skip composer checking if the required extensions are indeed installed. Useful for building the application on a server which is not the "live server" (which should be the case).

b) even more useful is the `config.platform` configuration, where you can specify in your `composer.json` the exact setup of your "live server", thus telling composer update (and install) that it should consider "this PHP version installed with this extensions" when dealing with the packages, even thou the current PHP version and extension list does not comply with it (as usually a CI system would):

In your project:
```
composer config platform.php "7.2.11"
composer config platform.ext-redis "*"
```

Results in:
```
    "config": {
        "platform": {
            "php": "7.2.11",
            "ext-redis": "*"
        }
    }
```

Future "composer install" and "composer update" will consider that you are running PHP 7.2.11 with "redis" extension installed, thus you can also install packages requiring "ext-redis" even thou the CI system doesn't have it installed.
 
See also: https://getcomposer.org/doc/06-config.md#platform

**Comment by g105b** [comment]
Thanks @baschny , you've taught me some new things there.

I agree that we shouldn't have to install packages for every possibility, but currently I am learning how to provide a rock-solid PHP base image for actions to run on, and I assumed I had missed some vital points.

I can imagine that a lot of unit tests will indeed require the presence of certain packages. For things like MySQL, there shouldn't really be any need to have an _actual_ database installed on the CI test runner, as everything like that would be mocked, but I can imagine that it's not the case for every scenario.

I think your solution is useful and I'll add this to the README when I have time, but I wonder if you could comment on my suggestion of installing _certain_ packages in the base docker image? I'm not sure what packages _should_ be installed by default for the CI test runners.

**Comment by baschny** [comment]
All right, this issue appeared in the "composer" sub-project, so my answer of course only covers this use-case, where you only really need [the extensions composer requires](https://github.com/composer/composer/blob/master/composer.json#L44) (zip, openssl, zlib). Having just "what you need" doesn't add extra bloat to the images, making the run go faster.

So I am more a fan of having separate images for separate purposes, to avoid them becoming to "fat". Of course a generic base must include a certain set of "expected" packages, and then upon that enhance with other extensions for certain use-cases. For the phpunit case you are right, everyone might need different extensions. phpstan on the other hand (just like composer) only need certain ones for the tool to run.

One idea would be to create a hierarchy of images, just a random thought:

* php-base with composer (in all php version flavors with choosable composer version)
  * phpstan (with a fixed set of extensions)
  * php-base + "common extensions" already installed (activatable through settings) 
    * behat
    * phpunit
...

We have been using the official PHP images + this project https://github.com/mlocati/docker-php-extension-installer to ease the installation of extensions (while still creating the smallest possible docker images due to very small layers!).

**Comment by flexchar** [comment]
Since you already working on it, I will just write here instead creating new issue. ZIP Extension should be installed next to composer.

> As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
> This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost. Installing 'unzip' may remediate them.

**Comment by g105b** [comment]
zip and git are installed by default on the base image that is under construction. There is one last task to complete before I release the next version of this action, but it's looking really positive - build times that execute within 10-30 seconds rather than minutes.

**Comment by g105b** [comment]
Released as v5 :)
