### ISSUE TITLE
http-basic auth to private repo?

### ISSUE THREAD

**Issue by aaronware** [php-actions/composer#42]
Quick Q: While I understand SSH is a better approach to authentication. In a scenario where that is not available. Can http-basic auth still be used? I tried a few permutations and it didn't seem to allow this approach. I would think that the action would allow something that composer itself allows? But more than likely I am doing it wrong?

I setup a step within my job authenticating utilzing the `with: command:` referencing a few github secrets. But the authentication always seems to fail.

**Comment by g105b** [comment]
Hi @aaronware ,

Thanks for your first issue report. HTTP basic auth is something I haven't personally used with Composer because, as you say, SSH is always preferred, but if it works locally for you with HTTP basic auth then I too would expect that this action behaves the same.

The best thing I can do is add a test in https://github.com/php-actions/example-composer to install a private repo using HTTP basic auth. There is already a test for SSH, so there isn't too much for me to set up.

This way we'll be able to see if there's a missing feature of this action, or whether your command needs tweaking. Before I begin, please could you share as much of your yaml configuration with me as possible (specifically the `with:` section, redacted where necessary)?

Thanks,
Greg.

**Comment by g105b** [comment]
Hi @aaronware ,

I've taken a look into this as I hadn't used HTTP basic authentication before now. It seems that the reason it is not preferred to use HTTP basic auth is because the credentials have to be placed into the URL of the repository, which must be referenced in the composer.json file, rather than passed into the action as an input from Github Secrets.

I just had success installing a private repo via HTTP basic auth with the following composer.json:

```json
{
	"name": "php-actions/example-composer",
	"description": "An example project that uses php-actions/composer",

	"repositories": [
		{
			"type": "vcs",
			"url": "https://g105b:a28ef1cb4582de-redacted@github.com/php-actions/example-private-repo"
		}
	],

	"require": {
		"phpgt/webengine": "dev-master",
		"php-actions/example-private-repo": "dev-master"
	}
}
```

The install goes smoothly, but my personal access token is in the URL in plain text, which is not good, especially if the project is to be open source.

I hope this clarifies what you're looking for. In short, yes it's possible, and you can use a [PAT on your Github account](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) for this, and include it in the URL for Composer to use, but it's really easy to [set up a deploy key for this](https://docs.github.com/en/developers/overview/managing-deploy-keys) and pass that into your action using [Github Secrets](https://docs.github.com/en/actions/reference/encrypted-secrets).

**Comment by g105b** [comment]
After reading [the Composer docs on Authentication](https://getcomposer.org/doc/articles/authentication-for-private-packages.md#http-basic), it seems that you could still achieve this using your Github secret, by writing the secret to `auth.json` in your project. Let me hook this up in an example... bear with me.

**Comment by g105b** [comment]
I have a working solution for you!

Step 1)
Create your personal access token
![image](https://user-images.githubusercontent.com/358014/105986399-c915af80-6094-11eb-9a71-42312b7babc4.png)

Step 2)
Add the following JSON as a secret to your repository - note you must match the hostname of the git server (in this case github.com) and your username and the PAT you just created
![image](https://user-images.githubusercontent.com/358014/105986423-d337ae00-6094-11eb-821e-1407cded974f.png)

Step 3)
Pass this secret to `auth.json` as a separate action step
![image](https://user-images.githubusercontent.com/358014/105986517-f4989a00-6094-11eb-9c51-44cc813b04e3.png)

Step 4)
Your action will now work!
![image](https://user-images.githubusercontent.com/358014/105986564-04b07980-6095-11eb-8e63-da67e73cff8c.png)


It's nice how Github actions redacts any mention of your access tokens in the runners. Nice and safe indeed.

I hope this works for you. Please let me know how you get on and we can close the issue.

**Comment by aaronware** [comment]
@g105b thanks so much for this. It worked perfectly!

**Comment by g105b** [comment]
No problem. I'll try and document this for future users.
