### ISSUE TITLE
No private keys supplied

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [php-actions/composer#59]
Hi all, for the first time I have problems with this amazing tool. 
I have already developed many githubActions using `php-actions/composer` but today I encountered a problem:

`No private keys supplied`

This is the complete log and you can find the output here:

https://github.com/PUGX/badge-poser/runs/2624411559?check_suite_focus=true

```
Running php-build composer
WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
Pulling docker.pkg.github.com/pugx/badge-poser/php-actions_composer_badge-poser:php-8-build2
WARNING: ⚠️ Failed to pull manifest by the resolved digest. This registry does not
	appear to conform to the distribution registry specification; falling back to
	pull by tag.  This fallback is DEPRECATED, and will be removed in a future
	release.  Please contact admins of https://docker.pkg.github.com. ⚠️

php-8-build2: Pulling from pugx/badge-poser/php-actions_composer_badge-poser
540db60ca938: Already exists
933cf2f4a68f: Pulling fs layer
93c5cc202a60: Pulling fs layer
74403c16157d: Pulling fs layer
ccb9776fa7b0: Pulling fs layer
5f4ca0d03106: Pulling fs layer
bd76023543a8: Pulling fs layer
77d0b61488f4: Pulling fs layer
57e642ce993f: Pulling fs layer
0dfccbae1c18: Pulling fs layer
ccb9776fa7b0: Waiting
5f4ca0d03106: Waiting
bd76023543a8: Waiting
77d0b61488f4: Waiting
57e642ce993f: Waiting
0dfccbae1c18: Waiting
93c5cc202a60: Verifying Checksum
93c5cc202a60: Download complete
933cf2f4a68f: Download complete
74403c16157d: Verifying Checksum
74403c16157d: Download complete
933cf2f4a68f: Pull complete
5f4ca0d03106: Verifying Checksum
5f4ca0d03106: Download complete
93c5cc202a60: Pull complete
74403c16157d: Pull complete
ccb9776fa7b0: Verifying Checksum
ccb9776fa7b0: Download complete
77d0b61488f4: Verifying Checksum
77d0b61488f4: Download complete
bd76023543a8: Verifying Checksum
bd76023543a8: Download complete
ccb9776fa7b0: Pull complete
57e642ce993f: Verifying Checksum
57e642ce993f: Download complete
5f4ca0d03106: Pull complete
0dfccbae1c18: Verifying Checksum
0dfccbae1c18: Download complete
bd76023543a8: Pull complete
77d0b61488f4: Pull complete
57e642ce993f: Pull complete
0dfccbae1c18: Pull complete
Digest: sha256:9123a4bddb7369bd8384ae1f28208da82bad86eec22bd7940ceed59c7c01c296
Status: Downloaded newer image for docker.pkg.github.com/pugx/badge-poser/php-actions_composer_badge-poser:php-8-build2
docker.pkg.github.com/pugx/badge-poser/php-actions_composer_badge-poser:php-8-build2
Docker tag: docker.pkg.github.com/pugx/badge-poser/php-actions_composer_badge-poser:php-8-build2
No private keys supplied
Command: composer install --no-progress --no-interaction --prefer-dist
Error: Process completed with exit code 1.
```

Can someone explain to me why am I getting this error?

I have also enabled the improved container support with the Container registry

Thanks.

**Comment by g105b** [comment]
Hi @AlessandroMinoccheri ,

I'll jump on this as soon as I get some time later. Not sure what can be causing the issue you're experiencing at the moment, but in the meantime, would you kindly look over the example project at https://github.com/php-actions/example-composer ?

Maybe you're using the master branch in your workflow, rather than the stable v5 release? I'm wondering because currently I'm in the middle of a change with how the php-build container passes around private information like keys.

Either way, I'll get some time later to assign to this.

Cheers,
Greg.

**Comment by AlessandroMinoccheri** [comment]
Hi @g105b 
I am using  v5 release at the moment.
It's a not clear problem and it's the first time that I encounter it.
How can I help you to solve this problem?

**Comment by g105b** [comment]
Hey, I think the issue is explained further up in the actions output. Composer isn't able to install your dependencies because certain extensions aren't available. Can you confirm that I'm understanding this correctly? 

I see errors about ext-gd not getting installed, etc... See the top of the error output.

You can install extensions by listing them in the config as explained here: https://github.com/php-actions/composer#including-php-extensions

Does this make sense? I want to make sure I'm not coming at this from the wrong angle.

Cheers,
Greg.

**Comment by AlessandroMinoccheri** [comment]
Ok, you are right, I added the extension inside the setup-php step not inside php-actions/composer.
The error about keys put me in the wrong way and I was focused on that instead of the extension.

Thanks a lot!

**Comment by g105b** [comment]
No problem, happy to hear your build is successful now. I'll take this into account and see if I can improve the readability of the error output.
