### ISSUE TITLE
Output.log : No such file or directory

### ISSUE THREAD

**Issue by rizvisx** [php-actions/composer#61]
Here's the composer action which I run

Run php-actions/composer@v5
  with:
    ssh_key_pub: ***
    version: latest
    php_version: latest
    command: install
    interaction: no
    dev: yes
    progress: no
    quiet: no
  env:

and it gives me this error.

cat: /home/ubuntu/runner/_work/xyz/xyz/output.log: No such file or directory

**Comment by LlZARD** [comment]
Still having it using v6

**Comment by WybeBaT** [comment]
Same issue for:

  php-stan:
    name: PHPStan
    runs-on: self-hosted
    container:
      image: ubuntu:20.04
      options: --rm

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Composer
        uses: php-actions/composer@v6
        with:
          php_version: 8.0
          version: 2

**Comment by g105b** [comment]
I'll take a look at this in the next couple of days.

**Comment by patie** [comment]
same problem

**Comment by g105b** [comment]
Hey @patie, @WybeBaT, @LlZARD, @rizvisx,

I've been experimenting with different build setups in the [example composer repository][example-composer] and I can't replicate this issue. I've made a new branch on the composer action too to see if I can help diagnose this issue.

What would really help me is if you could provide me with a link to an actions run that is failing in this way, or if that's not possible due to private repos, please can you try to use `composer@output-improvement` instead of `composer@v6`?

Thanks, and sorry for the delay in coming back to you... it's been a busy period for me.

Greg.

**Comment by mostafakram** [comment]
Hello @g105b I face the same issue when working on a container that include other services as mysql but it works fine if no container services are defined

**Comment by tobalsan** [comment]
Hey folks, 

I've got the same issue. I think it has happens when you run your workflow inside a container. 
The action uses the `${github.workspace}` variable, but [there's an opened issue](https://github.com/actions/runner/issues/2058) about the variable having an incorrect value inside a container.
