### ISSUE TITLE
Possible to specify version?

### ISSUE THREAD

**Issue by benjick** [php-actions/composer#8]
`XXX requires php ~7.1.3||~7.2.0 -> your PHP version (7.4.5) does not satisfy that requirement.`

Is it possible to specify somehow?

**Comment by g105b** [comment]
Maybe the version of XXX that your project requires can be increased? Does the dependency have more recent releases than the one that you are requiring?

It is technically possible to skip PHP or platform requirement checks (see https://getcomposer.org/doc/06-config.md#platform) but I would assume that the PHP version requirement is there for a reason.

**Comment by g105b** [comment]
Closing, because this repository does not enforce any PHP versions by itself.

**Comment by devsi** [comment]
I'd like to re-visit this issue. I am not able to use your package because the PHP version is not something that can be set. I'm not sure what your action defaults to, but currently it's set to `7.4.10` and my repo requires `7.3` due to PHPUnit constraints. I think it's fairly common for PHP versions to be locked in a composer json file, and is unrealistic for a lot of companies to have those restrictions removed.

Is this something you'd consider looking at?

**Comment by g105b** [comment]
Hi @devsi ,

Yes indeed. If it isn't working for you how you want it to, then it's an issue that needs resolving.

I'll re-think some things. Currently the action is based on the official Composer Docker image, but I think that will have to change. If I use a custom image just for php-actions, then we could have separate compiled PHP versions depending on yaml configurations. It might take a bit of time to get right, but I'll put this on the to-do list.

Any ideas, suggestions or commits are appreciated.

Cheers,
Greg.

**Comment by g105b** [comment]
I'm working on this issue this week. The solution is to use a custom base docker image that includes the different PHP configurations to choose from. I'm building this at github.com/php-actions/php

**Comment by g105b** [comment]
It's possible to specify the PHP version and Composer version in the action YML configuration now. Please see README for an example. 

However, this isn't the most ideal use of Github Actions' architecture. I've learnt a lot since starting these repositories, and soon you'll be able to take advantage of Docker layers so that you can specify all PHP extensions, PHP version, Composer version required, and builds will only take seconds to complete. See #27 for info on when this is completed (will ship as V5).
